#!/bin/bash
# GeoIP Database Download Helper Script

GEOIP_FILE="GeoLite2-City.mmdb"
CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GEOIP_PATH="${CURRENT_DIR}/${GEOIP_FILE}"

echo "========================================"
echo "GeoIP2 Database Download Helper"
echo "========================================"
echo ""

if [ -f "${GEOIP_PATH}" ]; then
    echo "✓ GeoIP database already exists at:"
    echo "  ${GEOIP_PATH}"
    echo ""
    echo "File size: $(du -h "${GEOIP_PATH}" | cut -f1)"
    echo "Last modified: $(stat -c %y "${GEOIP_PATH}" 2>/dev/null || stat -f %Sm "${GEOIP_PATH}" 2>/dev/null)"
    echo ""
    echo "To update, delete the file and run this script again."
    exit 0
fi

echo "⚠ GeoIP database NOT found at:"
echo "  ${GEOIP_PATH}"
echo ""
echo "The GeoLite2-City database is required for IP geolocation."
echo "Due to MaxMind licensing, you must download it manually."
echo ""
echo "========================================"
echo "DOWNLOAD INSTRUCTIONS"
echo "========================================"
echo ""
echo "1. Create a free MaxMind account:"
echo "   https://www.maxmind.com/en/geolite2/signup"
echo ""
echo "2. Log in and generate a license key:"
echo "   https://www.maxmind.com/en/accounts/current/license-key"
echo ""
echo "3. Download the GeoLite2-City database:"
echo "   https://www.maxmind.com/en/accounts/current/geoip/downloads"
echo "   - Select: GeoLite2 City"
echo "   - Format: MMDB (Binary)"
echo ""
echo "4. Extract and place the file:"
echo "   tar -xzf GeoLite2-City.tar.gz"
echo "   mv GeoLite2-City_*/GeoLite2-City.mmdb ${CURRENT_DIR}/"
echo ""
echo "========================================"
echo "AUTOMATED DOWNLOAD (with license key)"
echo "========================================"
echo ""
echo "If you have a license key, run:"
echo ""
echo "  LICENSE_KEY='your_license_key_here'"
echo "  wget \"https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=\${LICENSE_KEY}&suffix=tar.gz\" -O /tmp/GeoLite2-City.tar.gz"
echo "  tar -xzf /tmp/GeoLite2-City.tar.gz -C /tmp"
echo "  mv /tmp/GeoLite2-City_*/GeoLite2-City.mmdb ${CURRENT_DIR}/"
echo "  rm -rf /tmp/GeoLite2-City*"
echo ""
echo "========================================"
echo ""

exit 1
